# Generated by Django 4.0.7 on 2023-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studeninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(unique=True)),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_dob', models.DateField(max_length=15)),
                ('stu_address', models.CharField(max_length=200)),
                ('stu_phone', models.CharField(max_length=20)),
                ('stu_em_phone', models.CharField(max_length=20)),
                ('stu_class', models.CharField(max_length=20)),
            ],
        ),
    ]
