# Generated by Django 4.0.7 on 2023-06-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studeninfo',
            name='stu_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
