# Generated by Django 4.0.7 on 2023-06-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
